export const DISPLAY_ALERT  = 'SHOW_ALERT';
export const CLEAR_ALERT    = 'CLEAR_ALERT';

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';

export const CREATE_OP_BEGIN = 'CREATE_OP_BEGIN';
export const CREATE_OP_SUCCESS = 'CREATE_OP_SUCCESS';
export const CREATE_OP_ERROR = 'CREATE_OP_ERROR';

export const GET_OP_BEGIN = 'GET_OP_BEGIN';
export const GET_OP_SUCCESS = 'GET_OP_SUCCESS';
export const GET_OP_ERROR = 'GET_OP_ERROR';

export const SET_EDIT_OP = 'SET_EDIT_OP';

export const CLEAR_FORM_VALUES = 'CLEAR_FORM_VALUES';

export const DELETE_OP_BEGIN = 'DELETE_OP_BEGIN';

export const UPDATE_OP_BEGIN = 'UPDATE_OP_BEGIN';
export const UPDATE_OP_SUCCESS = 'UPDATE_OP_SUCCESS';
export const UPDATE_OP_ERROR = 'UPDATE_OP_ERROR';

//TODO:155 edit job front